### ISSUE TITLE
如何验证站点是否成功开启页面缓存？

### ISSUE THREAD

**Issue by WAGFS** [halo-sigs/plugin-page-cache#7]
大佬你好，请问站点在安装好插件后，除了看页面的响应时间还可以从哪些地方验证已经成功开启了页面缓存呢？页面响应头里有对应字段吗？🤔

**Comment by JohnNiang** [comment]
目前，如果经过了缓存，插件会在响应头里加上 X-Halo-Cache-At

**Comment by WAGFS** [comment]
> 目前，如果经过了缓存，插件会在响应头里加上 `X-Halo-Cache-At`。
> 
> 不过需要注意的是，只有匿名用户访问才会经过缓存，已登录用户访问是不会经过缓存的。
 好的💕

**Comment by Anyexyz** [comment]
> 目前，如果经过了缓存，插件会在响应头里加上 `X-Halo-Cache-At`。
> 
> 不过需要注意的是，只有匿名用户访问才会经过缓存，已登录用户访问是不会经过缓存的。

实测最新 1.1.0 版本中在未登录状态下未找到响应头 `X-Halo-Cache-At`

**Comment by JohnNiang** [comment]
> 实测最新 1.1.0 版本中在未登录状态下未找到响应头 X-Halo-Cache-At

实际上，一个页面在被未登录用户第一次访问时才会被缓存起来，并且并且不会返回响应头 `X-Halo-Cache-At`，只有在第二次访问的时候才会从缓存中直接获取，并返回该响应头。

/close
/kind support
