### ISSUE TITLE
【BUG】1.1.0 插件实际未启用

### ISSUE THREAD

**Issue by Anyexyz** [halo-sigs/plugin-page-cache#8]
据 #7 提到的："如果经过了缓存，插件会在响应头里加上 `X-Halo-Cache-At`"实测未找到，使用新环境 Halo-pro:2.18.1 + 插件 1.1.0 同样如此。
效果如下：
![fdca930e3701bbe27e89b6887ca945b](https://github.com/user-attachments/assets/41776c9a-78cd-48a2-892a-a9bf640b713d)

![image](https://github.com/user-attachments/assets/26126f5f-62a4-4818-a4b7-4af3c70937e5)

**Comment by JohnNiang** [comment]
想要击中缓存的条件有以下几点：

1. 请求头 `Accept` 必须包含 `text/html`，仅有 `*` 无效
2. 请求方法必须是 `GET`
3. 请求头 `Cache-Control` 中不能包含 `no-cache`
4. 请求用户是`匿名`的

目前尚不清楚 ITDOG 实际请求的请求头到底是怎么样的。所以无法判定是否是当前插件导致的问题

**Comment by JohnNiang** [comment]
Hi @Anyexyz ，请问匿名用户二次请求问题是否还存在呢？

/kind support
/remove-kind bug

**Comment by Anyexyz** [comment]
匿名二次请求没问题了，并发还需优化
